let
  ソース = Excel.Workbook(Web.Contents("https://www.jnto.go.jp/statistics/data/since2003_visitor_arrivals_July_2023.xlsx"), null, true),
  保持された上位の行 = Table.FirstN(ソース, 4),
  #"Data の展開 1" = Table.ExpandTableColumn(保持された上位の行, "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30"}),
  フィルター処理された行 = Table.SelectRows(#"Data の展開 1", each ([Column3] <> null)),
  #"フィルター処理された行 1" = Table.SelectRows(フィルター処理された行, each ([Column3] <> null)),
  マージされた列 = Table.CombineColumns(Table.TransformColumnTypes(#"フィルター処理された行 1", {{"Column1", type text}, {"Column2", type text}}), {"Column1", "Column2"}, Combiner.CombineTextByDelimiter("", QuoteStyle.None), "国名"),
  #"置き換えられた値 1" = Table.ReplaceValue(マージされた列, "　", "", Replacer.ReplaceText, {"国名"}),
  #"昇格されたヘッダー数 1" = Table.PromoteHeaders(#"置き換えられた値 1", [PromoteAllScalars = true]),
  列の選択 = Table.SelectColumns(#"昇格されたヘッダー数 1", {"2023", "", "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"}),
  名前が変更された列 = Table.RenameColumns(列の選択, {{"", "国名"}}),
  #"フィルター処理された行 2" = Table.SelectRows(名前が変更された列, each ([国名] <> "" and [国名] <> "アジア計" and [国名] <> "アフリカ計" and [国名] <> "オセアニア計" and [国名] <> "ヨーロッパ計" and [国名] <> "中東地域" and [国名] <> "北アメリカ計" and [国名] <> "北欧地域" and [国名] <> "南アメリカ計" and [国名] <> "総数")),
  ピボット解除された他の列 = Table.UnpivotOtherColumns(#"フィルター処理された行 2", {"2023", "国名"}, "属性", "値"),
  置き換えられた値 = Table.ReplaceValue(ピボット解除された他の列, "月", "/01", Replacer.ReplaceText, {"属性"}),
  追加されたカスタム = Table.AddColumn(置き換えられた値, "年月日", each [2023] & "/" & [属性]),
  変更された列タイプ = Table.TransformColumnTypes(追加されたカスタム, {{"年月日", type date}}),
  削除された列 = Table.RemoveColumns(変更された列タイプ, {"2023", "属性"}),
  #"名前が変更された列 1" = Table.RenameColumns(削除された列, {{"値", "人数"}}),
  #"変更された列タイプ 1" = Table.TransformColumnTypes(#"名前が変更された列 1", {{"人数", Int64.Type}}),
  アペンドされたクエリ = Table.Combine({#"変更された列タイプ 1", #"2003-2019"})
in
  アペンドされたクエリ