let
  ソース = Excel.Workbook(Web.Contents("https://www.jnto.go.jp/statistics/data/since2003_visitor_arrivals_July_2023.xlsx"), null, true),
  フィルター処理された行 = Table.SelectRows(ソース, each ([Name] = "2003" or [Name] = "2004" or [Name] = "2005" or [Name] = "2006" or [Name] = "2007" or [Name] = "2008" or [Name] = "2009" or [Name] = "2010" or [Name] = "2011" or [Name] = "2012" or [Name] = "2013" or [Name] = "2014" or [Name] = "2015" or [Name] = "2016" or [Name] = "2017" or [Name] = "2018" or [Name] = "2019")),
  #"Data の展開" = Table.ExpandTableColumn(フィルター処理された行, "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36"}),
  #"フィルター処理された行 1" = Table.SelectRows(#"Data の展開", each ([Column3] <> null)),
  昇格されたヘッダー数 = Table.PromoteHeaders(#"フィルター処理された行 1", [PromoteAllScalars = true]),
  変更された列タイプ = Table.TransformColumnTypes(昇格されたヘッダー数, {{"2019", Int64.Type}, {"Column2", type text}, {"1月", type any}, {"伸率", type any}, {"2月", type any}, {"伸率_1", type any}, {"3月", type any}, {"伸率_2", type any}, {"4月", type any}, {"伸率_3", type any}, {"5月", type any}, {"伸率_4", type any}, {"6月", type any}, {"伸率_5", type any}, {"7月", type any}, {"伸率_6", type any}, {"8月", type any}, {"伸率_7", type any}, {"9月", type any}, {"伸率_8", type any}, {"10月", type any}, {"伸率_9", type any}, {"11月", type any}, {"伸率_10", type any}, {"12月", type any}, {"伸率_11", type any}, {"累計", type any}, {"伸率_12", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}, {"Column37", type any}, {"2019_13", Int64.Type}, {"Sheet", type text}, {"false", type logical}}, "ja"),
  名前が変更された列 = Table.RenameColumns(変更された列タイプ, {{"2019", "年"}, {"Column2", "国名"}}),
  #"フィルター処理された行 2" = Table.SelectRows(名前が変更された列, each ([国名] <> null and [国名] <> "アジア計" and [国名] <> "アフリカ計" and [国名] <> "オセアニア計" and [国名] <> "ヨーロッパ計" and [国名] <> "北アメリカ計" and [国名] <> "南アメリカ計" and [国名] <> "総数")),
  列の選択 = Table.SelectColumns(#"フィルター処理された行 2", {"年", "国名", "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"}),
  ピボット解除された他の列 = Table.UnpivotOtherColumns(列の選択, {"年", "国名"}, "属性", "値"),
  #"変更された列タイプ 1" = Table.TransformColumnTypes(ピボット解除された他の列, {{"年", type text}}),
  置き換えられた値 = Table.ReplaceValue(#"変更された列タイプ 1", "月", "/01", Replacer.ReplaceText, {"属性"}),
  追加されたカスタム = Table.AddColumn(置き換えられた値, "年月日", each [年] & "/" & [属性]),
  #"変更された列タイプ 2" = Table.TransformColumnTypes(追加されたカスタム, {{"年月日", type date}}),
  削除された列 = Table.RemoveColumns(#"変更された列タイプ 2", {"年", "属性"}),
  #"変更された列タイプ 3" = Table.TransformColumnTypes(削除された列, {{"値", Int64.Type}}),
  #"名前が変更された列 1" = Table.RenameColumns(#"変更された列タイプ 3", {{"値", "人数"}})
in
  #"名前が変更された列 1"